// <auto-generated />
namespace AssignmentWCD_BabyFashionShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FistTim : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FistTim));
        
        string IMigrationMetadata.Id
        {
            get { return "202203161649247_FistTim"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
