// <auto-generated />
namespace AssignmentWCD_BabyFashionShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Hehe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Hehe));
        
        string IMigrationMetadata.Id
        {
            get { return "202203170913071_Hehe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
